export type ExecutiveQuestionGroup = {
  label: string;
  questions: readonly string[];
};

export const quickExecutiveQuestions = [
  "Como está minha família hoje?",
  "Faça um RX financeiro e patrimonial de hoje dentro do mês atual.",
  "Quais pendências são urgentes?",
  "Quais documentos vencem em breve?",
  "Quais exames estão atrasados?",
  "Quais são os próximos compromissos?",
] as const;

export const executiveQuestionGroups: readonly ExecutiveQuestionGroup[] = [
  {
    label: "Visão geral",
    questions: [
      "Como está minha família hoje?",
      "Qual é o resumo geral da família neste momento?",
      "Quais áreas da família precisam de mais atenção agora?",
      "Quais são as prioridades mais importantes desta semana?",
      "Quais pendências e compromissos devo acompanhar primeiro?",
      "O que aconteceu recentemente na família?",
      "Quais riscos e pendências aparecem no panorama geral?",
      "Como estão as finanças, tarefas e documentos da família?",
      "Quais são os principais números e alertas da família?",
      "Faça um RX financeiro e patrimonial de hoje dentro do mês atual.",
    ],
  },
  {
    label: "Finanças",
    questions: [
      "Qual é o resumo financeiro deste mês?",
      "Se o mês fechasse hoje, quanto entrou, quanto saiu e quanto sobraria provisionado?",
      "Como as receitas e despesas mudaram em relação ao mês anterior?",
      "Quais categorias de despesas mais cresceram neste mês?",
      "Quais são as maiores despesas da competência atual?",
      "Existe risco de déficit nos próximos meses?",
      "Quanto está planejado e quanto já foi realizado neste mês?",
      "Quais pagamentos estão vencidos ou vencem nos próximos 30 dias?",
      "Qual é a projeção de receitas e despesas para os próximos seis meses?",
      "Há sinais de queda de receita ou aumento relevante de despesas?",
    ],
  },
  {
    label: "Contas e fluxo de caixa",
    questions: [
      "Quais contas financeiras estão cadastradas e quais são seus saldos conhecidos?",
      "Quanto dinheiro disponível temos hoje nas contas?",
      "Qual é o saldo total conhecido das contas?",
      "Como o saldo inicial das contas participa da liquidez atual?",
      "A conta Cofre está incluída no saldo disponível?",
      "Quais contas estão sem saldo informado?",
      "Qual foi o fluxo de caixa realizado até agora?",
      "Quanto entrou e quanto saiu efetivamente das contas?",
      "As transferências entre contas estão alterando receitas ou despesas?",
      "Qual é a margem de liquidez diante dos compromissos futuros?",
    ],
  },
  {
    label: "Investimentos e patrimônio",
    questions: [
      "Qual é o valor atual conhecido dos investimentos?",
      "Quais investimentos possuem posição de mercado cadastrada?",
      "Qual é o custo conhecido e o ganho dos investimentos?",
      "Quais ativos estão sem valor de mercado atualizado?",
      "Como está distribuída a carteira de investimentos por tipo?",
      "Qual é a rentabilidade conhecida de cada investimento?",
      "Qual é o patrimônio líquido total conhecido da família?",
      "Quanto do patrimônio gera renda e quanto está destinado à moradia?",
      "O patrimônio consolidado está completo ou possui valores ausentes?",
      "Compare a liquidez financeira com o patrimônio imobiliário e os investimentos.",
    ],
  },
  {
    label: "Imóveis e aluguéis",
    questions: [
      "Quais imóveis estão cadastrados?",
      "Qual é o valor total do patrimônio imobiliário?",
      "Qual é o valor proporcional da família em cada imóvel?",
      "Quais imóveis possuem dívida cadastrada?",
      "Qual é o patrimônio imobiliário líquido conhecido?",
      "Quais contratos de aluguel estão ativos?",
      "Quais aluguéis precisam de reajuste?",
      "Existem contratos de locação sem próxima data de reajuste?",
      "Quais contratos de aluguel vencem nos próximos meses?",
      "Qual é o custo mensal estimado da vacância e a receita locatícia potencial?",
    ],
  },
  {
    label: "Tarefas e pendências",
    questions: [
      "Quais pendências são urgentes?",
      "Quais tarefas estão abertas?",
      "Quais tarefas estão atrasadas?",
      "Quais tarefas vencem primeiro?",
      "Quais tarefas possuem prioridade alta?",
      "Quem está responsável pelas tarefas abertas?",
      "Quais pendências precisam de ação nesta semana?",
      "Existem tarefas sem responsável ou sem prazo?",
      "Resuma as tarefas por prioridade e vencimento.",
      "Qual deve ser a ordem de execução das pendências atuais?",
    ],
  },
  {
    label: "Documentos",
    questions: [
      "Quais documentos vencem em breve?",
      "Quais documentos já estão vencidos?",
      "Quais documentos vencem nos próximos 90 dias?",
      "Quantos documentos estão cadastrados?",
      "Quais tipos de documentos temos cadastrados?",
      "Existem documentos sem data de validade?",
      "Quais documentos precisam de renovação primeiro?",
      "Há documentos com processamento pendente?",
      "Resuma a situação documental da família.",
      "Quais riscos documentais exigem atenção agora?",
    ],
  },
  {
    label: "Saúde",
    questions: [
      "Quais exames estão atrasados?",
      "Quais exames vencem ou precisam ser feitos em breve?",
      "Quais registros de saúde estão pendentes?",
      "Quantos exames precisam de atenção?",
      "Quais exames têm maior urgência pelo vencimento?",
      "Existem exames sem data de acompanhamento?",
      "Resuma os alertas de saúde da família.",
      "Quais pendências médicas aparecem no sistema?",
      "Quais exames estão próximos do prazo nos próximos 90 dias?",
      "Qual deve ser a prioridade para regularizar os exames pendentes?",
    ],
  },
  {
    label: "Agenda Google",
    questions: [
      "Quais são os próximos compromissos?",
      "O que está agendado para os próximos dias?",
      "Quais eventos aparecem primeiro na agenda?",
      "Tenho compromissos importantes em breve?",
      "Quais eventos da família estão no Google Calendar?",
      "Existe algum compromisso que exige preparação?",
      "Resuma os próximos eventos em ordem cronológica.",
      "Quais compromissos podem conflitar com pendências urgentes?",
      "O que devo preparar antes dos próximos compromissos?",
      "Monte uma agenda executiva dos próximos eventos.",
    ],
  },
  {
    label: "Pessoas e timeline",
    questions: [
      "Quais pessoas estão cadastradas na família?",
      "Quais membros da família estão ativos?",
      "Quais são os papéis das pessoas cadastradas?",
      "Existem pessoas com cadastro inativo ou pendente?",
      "Quantas pessoas fazem parte da família cadastrada?",
      "O que aconteceu recentemente na timeline da família?",
      "Quais foram os eventos mais recentes da família?",
      "Resuma o histórico recente da família.",
      "Quais acontecimentos recentes podem exigir acompanhamento?",
      "Combine as pessoas cadastradas com os eventos recentes da timeline.",
    ],
  },
  {
    label: "Jurídico",
    questions: [
      "Quais processos jurídicos estão ativos?",
      "Quantos processos legais precisam de acompanhamento?",
      "Quais processos tiveram atualização recente?",
      "Existem processos com prazo ou pendência próxima?",
      "Quais são os status dos processos cadastrados?",
      "Resuma a situação jurídica da família.",
      "Quais riscos jurídicos aparecem nos registros disponíveis?",
      "Quais processos devem ser acompanhados primeiro?",
      "Existem processos sem atualização recente?",
      "Monte um panorama executivo dos processos legais ativos.",
    ],
  },
] as const;
