import Link from "next/link";
import { redirect } from "next/navigation";
import { AssetDocumentUploadForm } from "@/app/components/asset-document-upload-form";
import { ConfirmSubmitButton } from "@/app/components/confirm-submit-button";
import { ExpandableCreateForm } from "@/app/components/expandable-create-form";
import { MainNav } from "@/app/components/main-nav";
import { SubmitButton } from "@/app/components/submit-button";
import { deleteAssetDocument } from "@/app/patrimonio-documentos/actions";
import { archiveInsurancePolicy, createInsurancePolicy, updateInsurancePolicy } from "@/app/seguros/actions";
import { getActionErrorMessage } from "@/lib/action-feedback";
import { getDocumentProcessingLabel } from "@/lib/document-intake/status";
import { canAdminFamily, canEditFamily, getFamilyContext } from "@/lib/family/context";
import { createClient } from "@/lib/supabase/server";

type PageProps = { searchParams: { success?: string; error?: string; request_id?: string; count?: string } };
type Policy = { id:string; title:string; insurance_type:string; policy_number:string|null; insurer:string; broker:string|null; start_date:string; end_date:string; insured_amount:number|null; premium_amount:number|null; deductible_amount:number|null; payment_frequency:string|null; status:string; insured_description:string|null; notes:string|null };
type LinkRow = { policy_id:string; target_type:string; person_id:string|null; property_id:string|null; vehicle_id:string|null; credit_card_id:string|null };
type Named = { id:string; name:string };
type Person = { id:string; first_name:string; last_name:string };
type Property = { id:string; title:string };
type Vehicle = { id:string; title:string; make:string; model:string; plate:string|null };
type Document = { id:string; insurance_policy_id:string; title:string; document_type:string; processing_status:string; metadata:Record<string,unknown>|null };

const TYPES = [["vehicle","Automóvel"],["property","Imóvel"],["personal","Pessoal"],["life","Vida"],["health","Saúde"],["travel","Viagem"],["card","Cartão"],["other","Outro"]] as const;
const STATUS = [["pending","Pendente"],["active","Vigente"],["expired","Vencido"],["cancelled","Cancelado"],["archived","Arquivado"]] as const;
const FREQUENCIES = [["","Periodicidade do pagamento"],["single","Pagamento único"],["monthly","Mensal"],["quarterly","Trimestral"],["semiannual","Semestral"],["annual","Anual"],["other","Outra"]] as const;
const DOCUMENT_TYPES = ["Apólice de Seguro", "Endosso", "Comprovante de Pagamento", "Condições Gerais", "Cartão do Segurado", "Outro"];
const typeLabel = new Map<string,string>(TYPES);
const statusLabel = new Map<string,string>(STATUS);

function currency(value:number|null) { return value === null ? "Não informado" : new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value); }
function date(value:string) { return new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)); }
function successMessage(success?:string,count?:string) { if(success==="created")return "Seguro cadastrado com sucesso."; if(success==="updated")return "Seguro atualizado com sucesso."; if(success==="archived")return "Seguro arquivado com sucesso."; if(success==="document_deleted")return "Documento excluído com sucesso."; if(success==="document_uploaded")return "Documento revisado e vinculado ao seguro."; if(success==="documents_archived")return `${count??"1"} arquivo(s) arquivado(s) sem OCR.`; return null; }

function TargetOptions({ people, properties, vehicles, cards }:{people:Person[];properties:Property[];vehicles:Vehicle[];cards:Named[]}) {
  return <><option value="">Bem ou pessoa segurada (opcional)</option><optgroup label="Pessoas">{people.map(item=><option key={`person:${item.id}`} value={`person:${item.id}`}>{item.first_name} {item.last_name}</option>)}</optgroup><optgroup label="Automóveis">{vehicles.map(item=><option key={`vehicle:${item.id}`} value={`vehicle:${item.id}`}>{item.title} — {item.make} {item.model}</option>)}</optgroup><optgroup label="Imóveis">{properties.map(item=><option key={`property:${item.id}`} value={`property:${item.id}`}>{item.title}</option>)}</optgroup><optgroup label="Cartões">{cards.map(item=><option key={`credit_card:${item.id}`} value={`credit_card:${item.id}`}>{item.name}</option>)}</optgroup></>;
}

function linkValue(link:LinkRow|undefined) { if(!link)return ""; if(link.person_id)return `person:${link.person_id}`; if(link.vehicle_id)return `vehicle:${link.vehicle_id}`; if(link.property_id)return `property:${link.property_id}`; if(link.credit_card_id)return `credit_card:${link.credit_card_id}`; return ""; }

export default async function SegurosPage({searchParams}:PageProps) {
  const context=await getFamilyContext(); const {user,family}=context; if(!user)redirect("/login"); if(!family)redirect("/dashboard?setup=required");
  const db=createClient();
  const [{data:policiesData,error:policiesError},{data:linksData},{data:peopleData},{data:propertiesData},{data:vehiclesData},{data:cardsData},{data:documentsData}]=await Promise.all([
    db.from("insurance_policies").select("id,title,insurance_type,policy_number,insurer,broker,start_date,end_date,insured_amount,premium_amount,deductible_amount,payment_frequency,status,insured_description,notes").eq("family_id",family.id).is("deleted_at",null).order("end_date"),
    db.from("insurance_policy_links").select("policy_id,target_type,person_id,property_id,vehicle_id,credit_card_id").eq("family_id",family.id),
    db.from("people").select("id,first_name,last_name").eq("family_id",family.id).is("deleted_at",null).order("first_name"),
    db.from("properties").select("id,title").eq("family_id",family.id).is("deleted_at",null).order("title"),
    db.from("vehicles").select("id,title,make,model,plate").eq("family_id",family.id).is("deleted_at",null).order("title"),
    db.from("credit_cards").select("id,name").eq("family_id",family.id).is("deleted_at",null).order("name"),
    db.from("documents").select("id,insurance_policy_id,title,document_type,processing_status,metadata").eq("family_id",family.id).not("insurance_policy_id","is",null).order("created_at",{ascending:false}),
  ]);
  const policies=(policiesData??[]) as Policy[]; const links=(linksData??[]) as LinkRow[]; const people=(peopleData??[]) as Person[]; const properties=(propertiesData??[]) as Property[]; const vehicles=(vehiclesData??[]) as Vehicle[]; const cards=(cardsData??[]) as Named[]; const documents=(documentsData??[]) as Document[];
  const names=new Map<string,string>([...people.map(item=>[`person:${item.id}`,`${item.first_name} ${item.last_name}`] as const),...properties.map(item=>[`property:${item.id}`,item.title] as const),...vehicles.map(item=>[`vehicle:${item.id}`,`${item.title} — ${item.make} ${item.model}`] as const),...cards.map(item=>[`credit_card:${item.id}`,item.name] as const)]);
  const today=new Date().toISOString().slice(0,10); const active=policies.filter(item=>item.status==="active"&&item.end_date>=today).length; const expiring=policies.filter(item=>item.status==="active"&&item.end_date>=today&&item.end_date<=new Date(Date.now()+30*86400000).toISOString().slice(0,10)).length;
  const canEdit=canEditFamily(context); const canAdmin=canAdminFamily(context); const message=successMessage(searchParams.success,searchParams.count);
  return <main className="min-h-screen bg-slate-50 p-6 md:p-10"><div className="mx-auto max-w-6xl space-y-6">
    <header className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><MainNav current="seguros"/><div><h1 className="text-2xl font-semibold text-slate-900">Seguros</h1><p className="mt-1 text-slate-600">Apólices, coberturas e vencimentos da família {family.name}.</p></div><div className="grid grid-cols-2 gap-3 sm:max-w-md"><div className="rounded-xl bg-emerald-50 p-3"><p className="text-xs text-emerald-700">Vigentes</p><p className="text-xl font-semibold text-emerald-950">{active}</p></div><div className="rounded-xl bg-amber-50 p-3"><p className="text-xs text-amber-700">Vencem em 30 dias</p><p className="text-xl font-semibold text-amber-950">{expiring}</p></div></div></header>
    {(message||searchParams.error)&&<section role={searchParams.error?"alert":"status"} className={`rounded-xl border px-4 py-3 text-sm ${searchParams.error?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{searchParams.error?getActionErrorMessage(searchParams.error,searchParams.request_id):message}</section>}
    {canEdit&&<ExpandableCreateForm id="create-policy" title="Cadastrar seguro" buttonLabel="NOVO SEGURO" submitAction={createInsurancePolicy} outcome={searchParams.error?"error":searchParams.success==="created"?"success":null} formClassName="grid grid-cols-1 gap-3 md:grid-cols-2">
      <input name="title" required placeholder="Título da apólice" className="rounded-xl border border-slate-300 px-3 py-2"/><select name="insurance_type" required className="rounded-xl border border-slate-300 px-3 py-2">{TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>
      <input name="policy_number" placeholder="Número da apólice" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="insurer" required placeholder="Seguradora" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="broker" placeholder="Corretora ou contato" className="rounded-xl border border-slate-300 px-3 py-2"/><select name="insured_target" className="rounded-xl border border-slate-300 px-3 py-2"><TargetOptions people={people} properties={properties} vehicles={vehicles} cards={cards}/></select>
      <label className="text-sm text-slate-600">Início da vigência<input name="start_date" type="date" required className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><label className="text-sm text-slate-600">Fim da vigência<input name="end_date" type="date" required className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label>
      <input name="insured_amount" inputMode="decimal" placeholder="Valor segurado" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="premium_amount" inputMode="decimal" placeholder="Valor pago / prêmio" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="deductible_amount" inputMode="decimal" placeholder="Franquia" className="rounded-xl border border-slate-300 px-3 py-2"/><select name="payment_frequency" className="rounded-xl border border-slate-300 px-3 py-2">{FREQUENCIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>
      <select name="status" className="rounded-xl border border-slate-300 px-3 py-2">{STATUS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input name="insured_description" placeholder="Descrição complementar do segurado/bem" className="rounded-xl border border-slate-300 px-3 py-2"/><textarea name="notes" rows={2} placeholder="Observações" className="rounded-xl border border-slate-300 px-3 py-2 md:col-span-2"/><div className="md:col-span-2"><SubmitButton label="Salvar seguro" className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white"/></div>
    </ExpandableCreateForm>}
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-900">Apólices cadastradas</h2><span className="text-sm text-slate-500">{policies.length}</span></div>
      {policiesError?<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">Não foi possível carregar os seguros. A migration do módulo pode estar pendente.</p>:policies.length===0?<p className="mt-4 rounded-xl bg-slate-50 p-4 text-slate-600">Nenhum seguro cadastrado.</p>:<div className="mt-4 space-y-3">{policies.map(policy=>{const policyLink=links.find(link=>link.policy_id===policy.id); const target=linkValue(policyLink); const policyDocuments=documents.filter(document=>document.insurance_policy_id===policy.id); const expired=policy.end_date<today; return <details key={policy.id} className="rounded-xl border border-slate-200 p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4"><div><p className="font-medium text-slate-900">{policy.title}</p><p className="text-sm text-slate-600">{typeLabel.get(policy.insurance_type)??policy.insurance_type} · {policy.insurer}</p></div><div className="text-right"><p className={`text-sm font-medium ${expired?"text-red-700":"text-slate-900"}`}>{expired?"Vencido":statusLabel.get(policy.status)??policy.status}</p><p className="text-xs text-slate-500">até {date(policy.end_date)}</p></div></summary><div className="mt-4 space-y-4">
        <div className="grid grid-cols-1 gap-2 rounded-xl bg-slate-50 p-4 text-sm text-slate-700 sm:grid-cols-2"><p>Apólice: {policy.policy_number??"Não informada"}</p><p>Segurado/bem: {names.get(target)??policy.insured_description??"Não informado"}</p><p>Cobertura: {currency(policy.insured_amount)}</p><p>Valor pago: {currency(policy.premium_amount)}</p></div>
        {canEdit&&<form action={updateInsurancePolicy} className="grid grid-cols-1 gap-3 md:grid-cols-2"><input type="hidden" name="policy_id" value={policy.id}/><input name="title" required defaultValue={policy.title} className="rounded-xl border border-slate-300 px-3 py-2"/><select name="insurance_type" defaultValue={policy.insurance_type} className="rounded-xl border border-slate-300 px-3 py-2">{TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input name="policy_number" defaultValue={policy.policy_number??""} placeholder="Número da apólice" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="insurer" required defaultValue={policy.insurer} placeholder="Seguradora" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="broker" defaultValue={policy.broker??""} placeholder="Corretora" className="rounded-xl border border-slate-300 px-3 py-2"/><select name="insured_target" defaultValue={target} className="rounded-xl border border-slate-300 px-3 py-2"><TargetOptions people={people} properties={properties} vehicles={vehicles} cards={cards}/></select><label className="text-sm text-slate-600">Início<input name="start_date" type="date" required defaultValue={policy.start_date} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><label className="text-sm text-slate-600">Fim<input name="end_date" type="date" required defaultValue={policy.end_date} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><input name="insured_amount" defaultValue={policy.insured_amount??""} placeholder="Valor segurado" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="premium_amount" defaultValue={policy.premium_amount??""} placeholder="Valor pago" className="rounded-xl border border-slate-300 px-3 py-2"/><input name="deductible_amount" defaultValue={policy.deductible_amount??""} placeholder="Franquia" className="rounded-xl border border-slate-300 px-3 py-2"/><select name="payment_frequency" defaultValue={policy.payment_frequency??""} className="rounded-xl border border-slate-300 px-3 py-2">{FREQUENCIES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select name="status" defaultValue={policy.status} className="rounded-xl border border-slate-300 px-3 py-2">{STATUS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input name="insured_description" defaultValue={policy.insured_description??""} placeholder="Descrição complementar" className="rounded-xl border border-slate-300 px-3 py-2"/><textarea name="notes" defaultValue={policy.notes??""} rows={2} placeholder="Observações" className="rounded-xl border border-slate-300 px-3 py-2 md:col-span-2"/><div className="md:col-span-2"><SubmitButton label="Salvar alterações" className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white"/></div></form>}
        <section className="rounded-2xl border border-blue-100 bg-blue-50/40 p-4"><h3 className="font-medium text-slate-900">Arquivos da apólice ({policyDocuments.length})</h3>{canEdit&&<AssetDocumentUploadForm familyId={family.id} entityId={policy.id} entityType="insurance_policy" documentTypes={DOCUMENT_TYPES}/>} {policyDocuments.length===0?<p className="mt-4 text-sm text-slate-500">Nenhum arquivo vinculado.</p>:<div className="mt-4 space-y-2">{policyDocuments.map(document=><div key={document.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-slate-900">{document.title}</p><p className="text-xs text-slate-500">{document.document_type} · {getDocumentProcessingLabel(document.processing_status,document.metadata)}</p></div><div className="flex flex-wrap gap-2"><Link href={`/documentos/${document.id}/download`} className="rounded-lg border border-blue-200 px-3 py-1.5 text-xs font-medium text-blue-700">Baixar</Link><Link href={`/documentos/${document.id}/revisar`} className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700">Revisar</Link>{canAdmin&&<form action={deleteAssetDocument}><input type="hidden" name="entity_type" value="insurance_policy"/><input type="hidden" name="entity_id" value={policy.id}/><input type="hidden" name="document_id" value={document.id}/><ConfirmSubmitButton label="Excluir" confirmMessage="Excluir este arquivo privado da apólice?" className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-medium text-red-700"/></form>}</div></div>)}</div>}</section>
        {canAdmin&&<form action={archiveInsurancePolicy}><input type="hidden" name="policy_id" value={policy.id}/><ConfirmSubmitButton label="Arquivar seguro" confirmMessage="Arquivar esta apólice? Os documentos continuarão preservados." className="rounded-xl border border-red-200 px-3 py-2 text-sm font-medium text-red-700"/></form>}
      </div></details>})}</div>}
    </section>
  </div></main>;
}
