import Link from "next/link";
import { createInvestmentAsset, createInvestmentPosition, createLease, createOwnerShare, createPropertyUnit, updateInvestmentAsset, updateProperty } from "@/app/financas/actions";
import type { FinanceWorkspace } from "@/lib/finance/types";
import { ArchiveForm, currency, Empty, field, formatDate, FormPanel, monthLabel, Options, panel, SaveButton } from "@/app/financas/views/shared";

type Access = { canEdit: boolean; canAdmin: boolean };

function propertyIdentity(title: string, address: string) {
  return `${title} ${address}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR").replace(/[^a-z0-9]/g, "");
}

export function PropertiesView({ workspace, canEdit, canAdmin }: { workspace: FinanceWorkspace } & Access) {
  const people = workspace.people.map((person) => ({ id: person.id, label: `${person.first_name} ${person.last_name}` }));
  const identityCounts = workspace.properties.reduce((counts, property) => {
    const key = propertyIdentity(property.title, property.address);
    counts.set(key, (counts.get(key) ?? 0) + 1);
    return counts;
  }, new Map<string, number>());
  const duplicateCount = workspace.properties.filter((property) => (identityCounts.get(propertyIdentity(property.title, property.address)) ?? 0) > 1).length;

  return <div className="space-y-5">
    <section className={`${panel} border-sky-200 bg-sky-50`}><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">Separação patrimonial</p><h2 className="mt-1 text-lg font-semibold text-slate-900">O imóvel cadastrado não gera receita automaticamente</h2><p className="mt-1 text-sm text-slate-600">O valor do contrato é apenas referência cadastral. Para entrar no caixa mensal, o aluguel precisa ser lançado como receita na Visão geral. Assim, um imóvel nunca duplica o recebível financeiro.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/imoveis#create-property" className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Cadastrar imóvel</Link><Link href="/financas?view=overview" className="rounded-xl border border-sky-300 bg-white px-4 py-2 text-sm font-semibold text-sky-800">Lançar aluguel recebido</Link></div></section>

    {duplicateCount > 0 && <section className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-900"><p className="font-semibold">Possíveis imóveis duplicados: {duplicateCount}</p><p className="text-sm">Registros com o mesmo nome e endereço estão marcados abaixo. Confira e use “Arquivar” no registro de teste; o histórico será preservado.</p></section>}

    {canEdit && <div className="grid gap-5 lg:grid-cols-3"><FormPanel title="Nova unidade"><form action={createPropertyUnit} className="grid gap-3"><select name="property_id" required className={field}><Options placeholder="Imóvel" rows={workspace.properties.map((item) => ({ id: item.id, label: item.title }))}/></select><input name="name" required placeholder="Nome" className={field}/><input name="code" required placeholder="Código" className={field}/><input name="unit_type" placeholder="Tipo" className={field}/><SaveButton/></form></FormPanel><FormPanel title="Contrato cadastral"><form action={createLease} className="grid gap-3"><select name="property_id" required className={field}><Options placeholder="Imóvel" rows={workspace.properties.map((item) => ({ id: item.id, label: item.title }))}/></select><select name="unit_id" className={field}><Options placeholder="Unidade" rows={workspace.units.map((item) => ({ id: item.id, label: item.name }))}/></select><select name="tenant_person_id" className={field}><Options placeholder="Locatário" rows={people}/></select><select name="principal_owner_person_id" className={field}><Options placeholder="Proprietário" rows={people}/></select><input name="start_date" required type="date" className={field}/><input name="end_date" type="date" className={field}/><input name="base_rent" required placeholder="Aluguel de referência" className={field}/><input name="charges_amount" placeholder="Encargos de referência" className={field}/><p className="text-xs text-slate-500">Não cria recebível no Financeiro.</p><SaveButton/></form></FormPanel><FormPanel title="Ratear proprietário"><form action={createOwnerShare} className="grid gap-3"><select name="lease_contract_id" required className={field}><Options placeholder="Contrato" rows={workspace.leases.map((item) => ({ id: item.id, label: `${workspace.properties.find((property) => property.id === item.property_id)?.title ?? "Imóvel"} · ${formatDate(item.start_date)}` }))}/></select><select name="person_id" required className={field}><Options placeholder="Proprietário" rows={people}/></select><select name="share_type" className={field}><option value="percentage">Percentual</option><option value="fixed_amount">Valor fixo</option></select><input name="percentage" placeholder="Percentual" className={field}/><input name="fixed_amount" placeholder="Valor fixo" className={field}/><input name="valid_from" required type="date" className={field}/><SaveButton/></form></FormPanel></div>}

    <section className={panel}><h2 className="font-semibold">Cadastro de imóveis</h2>{workspace.properties.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{workspace.properties.map((property) => {
      const possibleDuplicate = (identityCounts.get(propertyIdentity(property.title, property.address)) ?? 0) > 1;
      return <article key={property.id} className={`rounded-xl border p-4 ${possibleDuplicate ? "border-amber-300 bg-amber-50" : "border-slate-200"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{property.title}</p><p className="text-sm text-slate-500">{property.address}</p></div>{possibleDuplicate && <span className="rounded-full bg-amber-200 px-2 py-1 text-xs font-semibold text-amber-900">possível duplicado</span>}</div><p className="mt-3 text-xs text-slate-500">{workspace.units.filter((unit) => unit.property_id === property.id).length} unidades · {workspace.leases.filter((lease) => lease.property_id === property.id && lease.status === "active").length} contratos ativos · sem efeito automático no caixa</p>{canEdit && <FormPanel title="Editar cadastro"><form action={updateProperty} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={property.id}/><input name="title" required defaultValue={property.title} className={field}/><input name="address" required defaultValue={property.address} className={field}/><input name="city" defaultValue={property.city ?? ""} placeholder="Cidade" className={field}/><input name="state" defaultValue={property.state ?? ""} placeholder="UF" className={field}/><input name="postal_code" defaultValue={property.postal_code ?? ""} placeholder="CEP" className={field}/><input name="property_type" defaultValue={property.property_type ?? ""} placeholder="Tipo" className={field}/><input name="registry_number" defaultValue={property.registry_number ?? ""} placeholder="Matrícula" className={field}/><input name="municipal_registration" defaultValue={property.municipal_registration ?? ""} placeholder="Inscrição municipal" className={field}/><div className="flex flex-wrap gap-2 sm:col-span-2"><SaveButton/>{canAdmin && <ArchiveForm id={property.id} entity="property"/>}</div></form></FormPanel>}</article>;
    })}</div> : <Empty>Nenhum imóvel cadastrado.</Empty>}</section>
  </div>;
}

export function InvestmentsView({ workspace, competence, canEdit, canAdmin }: { workspace: FinanceWorkspace; competence: string } & Access) {
  const fieldsFor = (asset?: FinanceWorkspace["assets"][number]) => <><input name="name" required defaultValue={asset?.name} placeholder="Nome do investimento" className={field}/><input name="institution" required defaultValue={asset?.institution} placeholder="Instituição" className={field}/><select name="asset_type" defaultValue={asset?.asset_type ?? "fixed_income"} className={field}><option value="fixed_income">Renda fixa</option><option value="fund">Fundo</option><option value="cdb">CDB</option><option value="foreign_currency">Moeda estrangeira</option><option value="interest_account">Conta remunerada</option><option value="other">Outro</option></select><select name="account_id" defaultValue={asset?.account_id ?? ""} className={field}><Options placeholder="Conta vinculada (opcional)" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select></>;
  const monthEnd = new Date(Number(competence.slice(0, 4)), Number(competence.slice(5, 7)), 0).toISOString().slice(0, 10);
  const visiblePositions = workspace.positions.filter((position) => position.position_date <= monthEnd);
  const latestPositions = new Map<string, FinanceWorkspace["positions"][number]>();
  for (const position of visiblePositions) if (!latestPositions.has(position.asset_id)) latestPositions.set(position.asset_id, position);
  const total = workspace.assets.reduce((sum, asset) => sum + (latestPositions.get(asset.id)?.market_value ?? 0), 0);

  return <div className="space-y-5"><section className="rounded-3xl bg-gradient-to-r from-slate-950 to-sky-900 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-wider text-sky-200">Ativo consolidado · {monthLabel(competence)}</p><h2 className="mt-1 text-xl font-semibold">{workspace.assets.length} investimento(s)</h2><p className="mt-3 text-3xl font-semibold tabular-nums">{currency.format(total)}</p><p className="mt-2 text-sm text-slate-300">A soma usa o último saldo registrado até o fim do mês selecionado.</p></section>
    {canEdit && <FormPanel title="Novo investimento"><form action={createInvestmentAsset} className="grid gap-3 sm:grid-cols-2">{fieldsFor()}<div className="sm:col-span-2"><SaveButton label="Criar investimento"/></div></form></FormPanel>}
    <section className={panel}><h2 className="font-semibold">Investimentos e saldos</h2>{workspace.assets.length ? <div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{workspace.assets.map((asset) => {
      const positions = visiblePositions.filter((item) => item.asset_id === asset.id).sort((a, b) => b.position_date.localeCompare(a.position_date));
      const current = positions[0];
      return <article key={asset.id} className="rounded-xl border p-4"><p className="font-semibold">{asset.name}</p><p className="text-xs text-slate-500">{asset.institution} · {current ? `atualizado em ${formatDate(current.position_date)}` : `sem saldo até ${formatDate(monthEnd)}`}</p><p className="mt-4 text-xl font-semibold">{currency.format(current?.market_value ?? 0)}</p>{canEdit && <form action={createInvestmentPosition} className="mt-4 grid gap-2"><input type="hidden" name="asset_id" value={asset.id}/><label className="text-xs font-medium text-slate-600">Data do saldo<input name="position_date" required type="date" defaultValue={current?.position_date ?? monthEnd} className={`mt-1 w-full ${field}`}/></label><label className="text-xs font-medium text-slate-600">Saldo consolidado<input name="market_value" required inputMode="decimal" defaultValue={current?.market_value ?? ""} className={`mt-1 w-full ${field}`}/></label><SaveButton label="Atualizar saldo"/></form>}{canEdit && <FormPanel title="Dados do investimento"><form action={updateInvestmentAsset} className="grid gap-3"><input type="hidden" name="id" value={asset.id}/>{fieldsFor(asset)}<div className="flex flex-wrap gap-2"><SaveButton/>{canAdmin && <ArchiveForm id={asset.id} entity="asset"/>}</div></form></FormPanel>}</article>;
    })}</div> : <Empty>Nenhum investimento cadastrado.</Empty>}</section>
  </div>;
}
