import Link from "next/link";
import type { ReactNode } from "react";
import { createExchangeRate, createInvestmentAsset, createInvestmentPosition, createLease, createPropertyUnit, updateInvestmentAsset, updateLease, updateProperty } from "@/app/financas/actions";
import type { FinanceWorkspace } from "@/lib/finance/types";
import { ArchiveForm, currency, Empty, field, formatDate, FormPanel, monthLabel, Options, panel, SaveButton } from "@/app/financas/views/shared";

type Access = { canEdit: boolean; canAdmin: boolean };
type Lease = FinanceWorkspace["leases"][number];

function Field({ label, help, children, wide = false }: { label: string; help: string; children: ReactNode; wide?: boolean }) {
  return <label className={`text-xs font-medium text-slate-700 ${wide ? "sm:col-span-2" : ""}`}><span className="flex items-center gap-1">{label}<span title={help} className="grid h-4 w-4 cursor-help place-items-center rounded-full border text-[10px] text-slate-500">i</span></span><span className="mt-1 block">{children}</span></label>;
}

function LeaseFields({ workspace, lease }: { workspace: FinanceWorkspace; lease?: Lease }) {
  const people = workspace.people.map((p) => ({ id: p.id, label: `${p.first_name} ${p.last_name}` }));
  const units = workspace.units.filter((unit) => !lease || unit.property_id === lease.property_id);
  return <>
    <Field label="Imóvel" help="Bem patrimonial ao qual o contrato fica vinculado."><select name="property_id" required defaultValue={lease?.property_id ?? ""} className={field}><Options placeholder="Selecione" rows={workspace.properties.map((p) => ({ id: p.id, label: p.title }))}/></select></Field>
    <Field label="Unidade" help="Unidade locável; evita misturar contratos de imóveis diferentes."><select name="unit_id" defaultValue={lease?.unit_id ?? ""} className={field}><Options placeholder="Sem unidade específica" rows={units.map((u) => ({ id: u.id, label: u.name }))}/></select></Field>
    <Field label="Locatário" help="Pessoa relacionada ao contrato; não gera lançamento financeiro."><select name="tenant_person_id" defaultValue={lease?.tenant_person_id ?? ""} className={field}><Options placeholder="Não informado" rows={people}/></select></Field>
    <Field label="Proprietário principal" help="Responsável patrimonial principal pelo contrato."><select name="principal_owner_person_id" defaultValue={lease?.principal_owner_person_id ?? ""} className={field}><Options placeholder="Não informado" rows={people}/></select></Field>
    <Field label="Início" help="Referência do período contratual."><input name="start_date" required type="date" defaultValue={lease?.start_date ?? ""} className={field}/></Field>
    <Field label="Fim" help="Vazio significa prazo final não informado."><input name="end_date" type="date" defaultValue={lease?.end_date ?? ""} className={field}/></Field>
    <Field label="Aluguel-base" help="Valor cadastral; não cria recebível automaticamente."><input name="base_rent" required inputMode="decimal" defaultValue={lease?.base_rent ?? ""} className={field}/></Field>
    <Field label="Encargos" help="Encargos contratuais mantidos como referência."><input name="charges_amount" inputMode="decimal" defaultValue={lease?.charges_amount ?? 0} className={field}/></Field>
    <Field label="Índice de reajuste" help="Índice previsto, como IPCA ou IGP-M; não é aplicado sozinho."><input name="adjustment_index" defaultValue={lease?.adjustment_index ?? ""} placeholder="Ex.: IPCA" className={field}/></Field>
    <Field label="Frequência (meses)" help="Intervalo entre reajustes, normalmente 12 meses."><input name="adjustment_frequency_months" type="number" min="1" max="120" defaultValue={lease?.adjustment_frequency_months ?? ""} className={field}/></Field>
    <Field label="Próximo reajuste" help="Data confirmada usada nos alertas; o sistema não inventa a data."><input name="next_adjustment_date" type="date" defaultValue={lease?.next_adjustment_date ?? ""} className={field}/></Field>
    <Field label="Ocupação" help="Ativo conta como ocupado; vago entra nos dois indicadores de vacância."><select name="status" defaultValue={lease?.status ?? "active"} className={field}><option value="active">Ativo / ocupado</option><option value="vacant">Vago</option><option value="negotiating">Em negociação</option><option value="closed">Encerrado</option><option value="sold">Vendido</option></select></Field>
    <Field label="Garantia" help="Caução, fiador, seguro-fiança ou outra garantia."><input name="guarantee_type" defaultValue={lease?.guarantee_type ?? ""} className={field}/></Field>
    <Field label="Observações" help="Notas de revisão; não alteram cálculos."><input name="notes" defaultValue={lease?.notes ?? ""} className={field}/></Field>
  </>;
}

export function PropertiesView({ workspace, canEdit, canAdmin }: { workspace: FinanceWorkspace } & Access) {
  const active = workspace.leases.filter((lease) => lease.status === "active");
  const vacant = workspace.leases.filter((lease) => lease.status === "vacant");
  const activeRent = active.reduce((sum, lease) => sum + lease.base_rent, 0);
  const vacantPotential = vacant.reduce((sum, lease) => sum + lease.base_rent, 0);
  const financialVacancy = activeRent + vacantPotential ? vacantPotential / (activeRent + vacantPotential) * 100 : 0;
  const physicalVacancy = active.length + vacant.length ? vacant.length / (active.length + vacant.length) * 100 : 0;
  const reviewCount = active.filter((lease) => lease.review_status === "review_required").length;
  return <div className="space-y-5">
    <section className="grid gap-3 md:grid-cols-3"><article className={`${panel} border-amber-200 bg-amber-50`}><p className="text-xs font-semibold uppercase text-amber-700">Vacância financeira</p><p className="mt-2 text-2xl font-semibold">{financialVacancy.toFixed(1)}%</p><p className="text-xs text-slate-600">{currency.format(vacantPotential)} de potencial vago.</p></article><article className={`${panel} border-sky-200 bg-sky-50`}><p className="text-xs font-semibold uppercase text-sky-700">Vacância física</p><p className="mt-2 text-2xl font-semibold">{physicalVacancy.toFixed(1)}%</p><p className="text-xs text-slate-600">{vacant.length} de {active.length + vacant.length} unidades ativas ou vagas.</p></article><article className={`${panel} border-rose-200 bg-rose-50`}><p className="text-xs font-semibold uppercase text-rose-700">Revisão contratual</p><p className="mt-2 text-2xl font-semibold">{reviewCount}</p><p className="text-xs text-slate-600">Contratos ativos com reajuste incompleto.</p></article></section>
    <section className={`${panel} border-sky-200 bg-sky-50`}><p className="text-xs font-semibold uppercase text-sky-700">Integridade patrimonial e locatícia</p><h2 className="mt-1 text-lg font-semibold">Vínculos canônicos e histórico preservado</h2><p className="mt-1 text-sm text-slate-600">Contrato é cadastro; receita só entra no caixa por lançamento. Os relinks ficam registrados na auditoria.</p><div className="mt-3 flex gap-2"><Link href="/imoveis#create-property" className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Revisar patrimônio</Link><span className="rounded-xl border bg-white px-4 py-2 text-sm">{workspace.integrityAudit.length} evento(s) auditável(is)</span></div>{workspace.integrityAudit.length > 0 && <details className="mt-3 rounded-xl border border-sky-200 bg-white p-3"><summary className="cursor-pointer text-sm font-semibold text-sky-800">Ver trilha de integridade</summary><div className="mt-2 divide-y">{workspace.integrityAudit.map((audit) => <div key={audit.id} className="py-2 text-xs text-slate-600"><strong className="text-slate-800">{audit.entity_type}</strong> · {audit.status} · {new Date(audit.executed_at).toLocaleString("pt-BR")}{audit.source_id && audit.target_id && <span className="block break-all">Origem {audit.source_id} → destino {audit.target_id}</span>}</div>)}</div></details>}</section>
    {canEdit && <div className="grid gap-5 lg:grid-cols-2"><FormPanel title="Nova unidade"><form action={createPropertyUnit} className="grid gap-3"><select name="property_id" required className={field}><Options placeholder="Imóvel" rows={workspace.properties.map((p) => ({ id: p.id, label: p.title }))}/></select><input name="name" required placeholder="Nome da unidade" className={field}/><input name="code" required placeholder="Código" className={field}/><input name="unit_type" placeholder="Tipo" className={field}/><SaveButton/></form></FormPanel><FormPanel title="Novo contrato cadastral"><form action={createLease} className="grid gap-3 sm:grid-cols-2"><LeaseFields workspace={workspace}/><p className="text-xs text-slate-500 sm:col-span-2">Não cria recebível no Financeiro.</p><div className="sm:col-span-2"><SaveButton/></div></form></FormPanel></div>}
    <section className={panel}><h2 className="font-semibold">Contratos e reajustes</h2>{workspace.leases.length ? <div className="mt-4 space-y-3">{workspace.leases.map((lease) => <details key={lease.id} className={`rounded-xl border p-4 ${lease.review_status === "review_required" ? "border-amber-300 bg-amber-50" : "border-slate-200"}`}><summary className="cursor-pointer list-none"><strong>{workspace.properties.find((p) => p.id === lease.property_id)?.title ?? "Imóvel"}</strong><span className="ml-2 text-sm text-slate-600">{currency.format(lease.base_rent)} · {lease.status} · {lease.next_adjustment_date ? formatDate(lease.next_adjustment_date) : "reajuste pendente"}</span></summary>{canEdit && <form action={updateLease} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={lease.id}/><LeaseFields workspace={workspace} lease={lease}/><div className="sm:col-span-2"><SaveButton/></div></form>}</details>)}</div> : <Empty>Nenhum contrato cadastrado.</Empty>}</section>
    <section className={panel}><h2 className="font-semibold">Cadastro de imóveis</h2>{workspace.properties.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{workspace.properties.map((property) => <article key={property.id} className="rounded-xl border p-4"><p className="font-semibold">{property.title}</p><p className="text-sm text-slate-500">{property.address}</p><p className="mt-2 text-xs text-slate-500">{workspace.units.filter((unit) => unit.property_id === property.id).length} unidade(s) · participação {property.ownership_review_status === "confirmed" ? "confirmada" : "pendente"}</p>{canEdit && <FormPanel title="Editar identificação"><form action={updateProperty} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={property.id}/><input name="title" required defaultValue={property.title} className={field}/><input name="address" required defaultValue={property.address} className={field}/><input name="city" defaultValue={property.city ?? ""} placeholder="Cidade" className={field}/><input name="state" defaultValue={property.state ?? ""} placeholder="UF" className={field}/><input name="postal_code" defaultValue={property.postal_code ?? ""} placeholder="CEP" className={field}/><input name="property_type" defaultValue={property.property_type ?? ""} placeholder="Tipo" className={field}/><input name="registry_number" defaultValue={property.registry_number ?? ""} placeholder="Matrícula" className={field}/><input name="municipal_registration" defaultValue={property.municipal_registration ?? ""} placeholder="Inscrição municipal" className={field}/><div className="flex gap-2 sm:col-span-2"><SaveButton/>{canAdmin && <ArchiveForm id={property.id} entity="property"/>}</div></form></FormPanel>}</article>)}</div> : <Empty>Nenhum imóvel cadastrado.</Empty>}</section>
  </div>;
}

function nativeCurrency(currencyCode: string, amount: number) {
  try { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: currencyCode.trim() }).format(amount); } catch { return `${currencyCode} ${amount.toLocaleString("pt-BR")}`; }
}

export function InvestmentsView({ workspace, competence, canEdit, canAdmin }: { workspace: FinanceWorkspace; competence: string } & Access) {
  const assetFields = (asset?: FinanceWorkspace["assets"][number]) => <><Field label="Nome" help="Identificação do investimento."><input name="name" required defaultValue={asset?.name} className={field}/></Field><Field label="Instituição" help="Banco ou custodiante."><input name="institution" required defaultValue={asset?.institution} className={field}/></Field><Field label="Tipo" help="Classificação do relatório executivo."><select name="asset_type" defaultValue={asset?.asset_type ?? "fixed_income"} className={field}><option value="fixed_income">Renda fixa</option><option value="fund">Fundo</option><option value="cdb">CDB</option><option value="foreign_currency">Moeda estrangeira</option><option value="interest_account">Conta remunerada</option><option value="other">Outro</option></select></Field><Field label="Moeda" help="Moeda nativa; EUR e USD exigem cotação para consolidar."><select name="currency" defaultValue={asset?.currency.trim() ?? "BRL"} className={field}><option>BRL</option><option>USD</option><option>EUR</option></select></Field><Field label="Conta vinculada" help="Conta associada, quando aplicável."><select name="account_id" defaultValue={asset?.account_id ?? ""} className={field}><Options placeholder="Opcional" rows={workspace.accounts.map((a) => ({ id: a.id, label: a.institution }))}/></select></Field></>;
  const monthEnd = new Date(Date.UTC(Number(competence.slice(0, 4)), Number(competence.slice(5, 7)), 0)).toISOString().slice(0, 10);
  const latest = new Map<string, FinanceWorkspace["positions"][number]>();
  for (const position of workspace.positions.filter((p) => p.position_date <= monthEnd)) if (!latest.has(position.asset_id)) latest.set(position.asset_id, position);
  const totalBrl = workspace.assets.reduce((sum, asset) => sum + (latest.get(asset.id)?.market_value_brl ?? 0), 0);
  const pendingFx = workspace.assets.filter((asset) => asset.currency.trim() !== "BRL" && latest.get(asset.id)?.valuation_status !== "confirmed").length;
  return <div className="space-y-5"><section className="rounded-3xl bg-gradient-to-r from-slate-950 to-sky-900 p-6 text-white"><p className="text-xs font-semibold uppercase text-sky-200">Integridade cambial · {monthLabel(competence)}</p><h2 className="mt-1 text-xl font-semibold">Patrimônio financeiro confirmado em BRL</h2><p className="mt-3 text-3xl font-semibold">{currency.format(totalBrl)}</p><p className="mt-2 text-sm text-slate-300">{pendingFx ? `${pendingFx} posição(ões) estrangeira(s) aguardam confirmação.` : "Conversões visíveis confirmadas."}</p></section>
    {canEdit && <div className="grid gap-5 lg:grid-cols-2"><FormPanel title="Cadastrar cotação"><form action={createExchangeRate} className="grid gap-3 sm:grid-cols-2"><Field label="Moeda" help="Moeda convertida para BRL."><select name="currency" className={field}><option>USD</option><option>EUR</option></select></Field><Field label="Data" help="Data de referência da taxa."><input name="rate_date" type="date" required defaultValue={monthEnd} className={field}/></Field><Field label="Taxa para BRL" help="Reais por uma unidade da moeda."><input name="rate_to_brl" required inputMode="decimal" className={field}/></Field><Field label="Fonte" help="Marque PTAX somente após conferir no Banco Central."><select name="source" className={field}><option value="manual">Manual</option><option value="BCB_PTAX">BCB PTAX</option></select></Field><Field label="Referência" help="URL, boletim ou anotação para auditoria." wide><input name="source_reference" className={field}/></Field><div className="sm:col-span-2"><SaveButton label="Salvar cotação"/></div></form></FormPanel><FormPanel title="Novo investimento"><form action={createInvestmentAsset} className="grid gap-3 sm:grid-cols-2">{assetFields()}<div className="sm:col-span-2"><SaveButton label="Criar investimento"/></div></form></FormPanel></div>}
    <section className={panel}><h2 className="font-semibold">Cotações auditáveis</h2>{workspace.exchangeRates.length ? <div className="mt-3 flex flex-wrap gap-2">{workspace.exchangeRates.map((rate) => <span key={rate.id} className="rounded-full border border-sky-200 bg-sky-50 px-3 py-1.5 text-xs">{rate.currency.trim()} · {formatDate(rate.rate_date)} · R$ {rate.rate_to_brl} · {rate.source}</span>)}</div> : <Empty>Nenhuma cotação cadastrada.</Empty>}</section>
    <section className={panel}><h2 className="font-semibold">Investimentos e posições</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{workspace.assets.map((asset) => { const current = latest.get(asset.id); const code = asset.currency.trim(); const rates = workspace.exchangeRates.filter((r) => r.currency.trim() === code && r.rate_date <= monthEnd); return <article key={asset.id} className={`rounded-xl border p-4 ${current?.valuation_status === "review_required" ? "border-amber-300 bg-amber-50" : ""}`}><p className="font-semibold">{asset.name}</p><p className="text-xs text-slate-500">{asset.institution} · {code}</p><p className="mt-3 text-xl font-semibold">{current?.native_market_value == null ? "Valor nativo pendente" : nativeCurrency(code, current.native_market_value)}</p><p className="text-sm text-slate-600">{current?.market_value_brl == null ? "Conversão pendente" : `${currency.format(current.market_value_brl)} consolidado`}</p>{canEdit && <form action={createInvestmentPosition} className="mt-4 grid gap-2"><input type="hidden" name="asset_id" value={asset.id}/><Field label="Data da posição" help="Data do saldo."><input name="position_date" type="date" required defaultValue={current?.position_date ?? monthEnd} className={field}/></Field><Field label={`Valor nativo (${code})`} help="Não informe equivalente em reais."><input name="native_market_value" required inputMode="decimal" defaultValue={current?.native_market_value ?? ""} className={field}/></Field>{code !== "BRL" && <Field label="Cotação aplicada" help="A taxa fica copiada na posição para auditoria."><select name="exchange_rate_id" defaultValue={current?.exchange_rate_id ?? ""} className={field}><Options placeholder="Deixar pendente" rows={rates.map((r) => ({ id: r.id, label: `${formatDate(r.rate_date)} · R$ ${r.rate_to_brl}` }))}/></select></Field>}<SaveButton label="Atualizar posição"/></form>}{canEdit && <FormPanel title="Dados do investimento"><form action={updateInvestmentAsset} className="grid gap-3"><input type="hidden" name="id" value={asset.id}/>{assetFields(asset)}<div className="flex gap-2"><SaveButton/>{canAdmin && <ArchiveForm id={asset.id} entity="asset"/>}</div></form></FormPanel>}</article>; })}</div></section>
  </div>;
}
