import { createAccount, createCard, createCategory, updateAccount, updateCard, updateCategory } from "@/app/financas/actions";
import type { FinanceWorkspace } from "@/lib/finance/types";
import { ArchiveForm, currency, Empty, field, FormPanel, Options, panel, SaveButton } from "@/app/financas/views/shared";

type Access = { canEdit: boolean; canAdmin: boolean };

export function AccountsView({ workspace, canEdit, canAdmin }: { workspace: FinanceWorkspace } & Access) {
  const people = workspace.people.map((person) => ({ id: person.id, label: `${person.first_name} ${person.last_name}` }));
  return <div className="space-y-5">{canEdit && <FormPanel title="Nova conta"><form action={createAccount} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><input name="institution" required placeholder="Instituição" className={field}/><input name="account_type" required placeholder="Tipo de conta" className={field}/><input name="account_identifier" placeholder="Identificador" className={field}/><select name="owner_person_id" className={field}><Options placeholder="Titular" rows={people}/></select><input name="opening_balance" inputMode="decimal" placeholder="Saldo inicial" className={field}/><input name="opening_balance_date" type="date" className={field}/><div className="sm:col-span-2 lg:col-span-3"><SaveButton label="Criar conta"/></div></form></FormPanel>}<section className={panel}><h2 className="font-semibold">Contas</h2>{workspace.accounts.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{workspace.accounts.map((account) => <article key={account.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{account.institution}</p><p className="text-sm text-slate-500">{account.account_type} · {account.account_identifier ?? "sem identificador"}</p></div><p className="font-semibold">{currency.format(account.opening_balance)}</p></div>{canEdit && <FormPanel title="Editar conta"><form action={updateAccount} className="grid gap-3"><input type="hidden" name="id" value={account.id}/><input name="institution" required defaultValue={account.institution} className={field}/><input name="account_type" required defaultValue={account.account_type} className={field}/><input name="account_identifier" defaultValue={account.account_identifier ?? ""} className={field}/><select name="owner_person_id" defaultValue={account.owner_person_id ?? ""} className={field}><Options placeholder="Titular" rows={people}/></select><input name="opening_balance" defaultValue={account.opening_balance} className={field}/><input name="opening_balance_date" type="date" defaultValue={account.opening_balance_date ?? ""} className={field}/><div className="flex flex-wrap gap-2"><SaveButton/>{canAdmin && <ArchiveForm id={account.id} entity="account"/>}</div></form></FormPanel>}</article>)}</div> : <Empty>Nenhuma conta cadastrada.</Empty>}</section></div>;
}

export function CategoriesView({ workspace, canEdit, canAdmin }: { workspace: FinanceWorkspace } & Access) {
  return <div className="space-y-5">{canEdit && <FormPanel title="Nova categoria"><form action={createCategory} className="grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="Nome" className={field}/><select name="category_type" className={field}><option value="expense">Despesa</option><option value="income">Receita</option><option value="investment">Investimento</option><option value="transfer">Transferência</option><option value="adjustment">Ajuste</option></select><select name="parent_id" className={field}><Options placeholder="Categoria pai" rows={workspace.categories.map((item) => ({ id: item.id, label: item.name }))}/></select><input name="color" type="color" className={field}/><div className="sm:col-span-2"><SaveButton label="Criar categoria"/></div></form></FormPanel>}<section className={panel}><h2 className="font-semibold">Categorias</h2>{workspace.categories.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{workspace.categories.map((category) => <article key={category.id} className="rounded-xl border p-4"><p className="font-semibold">{category.name}</p><p className="text-xs text-slate-500">{category.category_type}{category.parent_id ? " · subcategoria" : ""}</p>{canEdit && <FormPanel title="Editar categoria"><form action={updateCategory} className="grid gap-3"><input type="hidden" name="id" value={category.id}/><input name="name" required defaultValue={category.name} className={field}/><select name="category_type" defaultValue={category.category_type} className={field}><option value="expense">Despesa</option><option value="income">Receita</option><option value="investment">Investimento</option><option value="transfer">Transferência</option><option value="adjustment">Ajuste</option></select><select name="parent_id" defaultValue={category.parent_id ?? ""} className={field}><Options placeholder="Categoria pai" rows={workspace.categories.filter((item) => item.id !== category.id).map((item) => ({ id: item.id, label: item.name }))}/></select><input name="color" type="color" defaultValue={category.color ?? "#64748b"} className={field}/><div className="flex gap-2"><SaveButton/>{canAdmin && <ArchiveForm id={category.id} entity="category"/>}</div></form></FormPanel>}</article>)}</div> : <Empty>Nenhuma categoria cadastrada.</Empty>}</section></div>;
}

export function CardsView({ workspace, canEdit, canAdmin }: { workspace: FinanceWorkspace } & Access) {
  const accounts = workspace.accounts.map((item) => ({ id: item.id, label: item.institution }));
  const fieldsFor = (card?: FinanceWorkspace["cards"][number]) => <><input name="name" required defaultValue={card?.name} placeholder="Nome do cartão" className={field}/><input name="institution" required defaultValue={card?.institution} placeholder="Instituição" className={field}/><input name="brand" defaultValue={card?.brand ?? ""} placeholder="Bandeira" className={field}/><input name="last_four" maxLength={4} defaultValue={card?.last_four ?? ""} placeholder="Últimos 4 dígitos" className={field}/><input name="credit_limit" inputMode="decimal" defaultValue={card?.credit_limit ?? ""} placeholder="Limite" className={field}/><input name="closing_day" type="number" min="1" max="31" defaultValue={card?.closing_day ?? ""} placeholder="Dia fechamento" className={field}/><input name="due_day" type="number" min="1" max="31" defaultValue={card?.due_day ?? ""} placeholder="Dia vencimento" className={field}/><input name="best_purchase_day" type="number" min="1" max="31" defaultValue={card?.best_purchase_day ?? ""} placeholder="Melhor dia" className={field}/><select name="payment_account_id" defaultValue={card?.payment_account_id ?? ""} className={field}><Options placeholder="Conta de pagamento" rows={accounts}/></select></>;
  return <div className="space-y-5">{canEdit && <FormPanel title="Novo cartão"><form action={createCard} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fieldsFor()}<div className="sm:col-span-2 lg:col-span-3"><SaveButton label="Criar cartão"/></div></form></FormPanel>}<section className={panel}><h2 className="font-semibold">Cartões</h2>{workspace.cards.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{workspace.cards.map((card) => { const used = workspace.entries.filter((entry) => entry.card_id === card.id && entry.entry_type === "expense" && !entry.deleted_at && entry.status !== "cancelled").reduce((sum, entry) => sum + entry.expected_amount, 0); return <article key={card.id} className="rounded-2xl border bg-gradient-to-br from-slate-950 to-sky-900 p-5 text-white"><p className="text-xs uppercase text-sky-200">{card.institution}</p><h3 className="mt-1 text-lg font-semibold">{card.name} ·•••• {card.last_four ?? "----"}</h3><p className="mt-5 text-xs text-slate-300">Limite disponível</p><p className="text-xl font-semibold">{currency.format(Math.max(0, (card.credit_limit ?? 0) - used))}</p><p className="mt-2 text-xs text-slate-300">Fecha {card.closing_day ?? "—"} · vence {card.due_day ?? "—"}</p>{canEdit && <FormPanel title="Editar cartão"><form action={updateCard} className="grid gap-3"><input type="hidden" name="id" value={card.id}/>{fieldsFor(card)}<div className="flex flex-wrap gap-2"><SaveButton/>{canAdmin && <ArchiveForm id={card.id} entity="card"/>}</div></form></FormPanel>}</article>; })}</div> : <Empty>Nenhum cartão cadastrado.</Empty>}</section></div>;
}
