import Link from "next/link";
import { ConfirmSubmitButton } from "@/app/components/confirm-submit-button";
import { DuplicateAmountForm } from "@/app/financas/duplicate-amount-form";
import { createBalanceAdjustment, createEntry, createTransfer, markEntryPaid, undoEntryPayment, updateEntry } from "@/app/financas/actions";
import { appendCursorTrail, previousCursorTrail } from "@/lib/finance/pagination";
import { currentCompetence } from "@/lib/finance/services";
import type { FinanceFilters, FinancialEntryPage, FinancialEntryRow, FinanceWorkspace } from "@/lib/finance/types";
import { ArchiveForm, currency, danger, Empty, EntryFields, field, FieldLabel, formatDate, FormPanel, Options, panel, primary, SaveButton } from "@/app/financas/views/shared";

type SearchParams = Record<string, string | string[] | undefined>;
function valueOf(params: SearchParams, key: string) { const value = params[key]; return Array.isArray(value) ? value[0] : value; }

function History({ workspace, entryId }: { workspace: FinanceWorkspace; entryId: string }) {
  const history = workspace.history.filter((item) => item.financial_entry_id === entryId);
  return <details className="mt-3 rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer text-xs font-semibold text-sky-700">Histórico somente leitura ({history.length})</summary>{history.length ? <ol className="mt-2 space-y-2">{history.map((item) => <li key={item.id} className="text-xs text-slate-600"><span className="font-medium">{item.change_type}</span> · {formatDate(item.changed_at)}</li>)}</ol> : <p className="mt-2 text-xs text-slate-500">Nenhuma alteração registrada.</p>}</details>;
}

function MovementCard({ workspace, entry, params, canEdit, canAdmin }: { workspace: FinanceWorkspace; entry: FinancialEntryRow; params: SearchParams; canEdit: boolean; canAdmin: boolean }) {
  const category = workspace.categories.find((item) => item.id === entry.category_id)?.name ?? "Sem categoria";
  const classification = workspace.categories.find((item) => item.id === entry.classification_category_id)?.name;
  const source = workspace.accounts.find((item) => item.id === entry.account_id)?.institution ?? workspace.cards.find((item) => item.id === entry.card_id)?.name ?? entry.origin;
  const returnCompetence = valueOf(params, "return_competence") ?? valueOf(params, "competence") ?? entry.competence.slice(0, 7);
  return <article className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{entry.description}</p><p className="text-xs text-slate-500">{formatDate(entry.expected_date ?? entry.due_date ?? entry.competence)} · {category}{classification ? ` · Tipo: ${classification}` : ""} · {source}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{entry.status}</span></div><dl className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-xs text-slate-500">Previsto</dt><dd>{currency.format(entry.expected_amount)}</dd></div><div><dt className="text-xs text-slate-500">Realizado</dt><dd>{entry.actual_amount === null ? "—" : currency.format(entry.actual_amount)}</dd></div><div><dt className="text-xs text-slate-500">Diferença</dt><dd>{entry.difference_amount === null ? "—" : currency.format(entry.difference_amount)}</dd></div></dl>{canEdit && <div className="mt-4 flex flex-wrap gap-2">{entry.actual_amount === null ? <form action={markEntryPaid} className="flex flex-wrap items-end gap-2"><input type="hidden" name="id" value={entry.id}/><input type="hidden" name="return_competence" value={returnCompetence}/><FieldLabel label="Valor realizado" help="Confirma o valor que efetivamente entrou ou saiu e substitui o previsto na realização."><input name="actual_amount" defaultValue={entry.expected_amount} className={`${field} block w-32`}/></FieldLabel><FieldLabel label="Data efetiva" help="Data em que o dinheiro entrou ou saiu e passou a afetar o saldo da conta."><input name="effective_date" type="date" required className={`block ${field}`}/></FieldLabel><SaveButton label="Realizar"/></form> : <form action={undoEntryPayment}><input type="hidden" name="id" value={entry.id}/><input type="hidden" name="return_competence" value={returnCompetence}/><ConfirmSubmitButton label="Desfazer pagamento" confirmMessage="Deseja desfazer o valor realizado deste lançamento?" className={danger}/></form>}{canAdmin && <ArchiveForm id={entry.id} entity="entry" returnView="movements" returnCompetence={returnCompetence}/>}</div>}<History workspace={workspace} entryId={entry.id}/>{canEdit && <FormPanel title="Editar lançamento"><form action={updateEntry} className="grid gap-3 md:grid-cols-4"><input type="hidden" name="id" value={entry.id}/>{valueOf(params, "return_view") && <input type="hidden" name="return_view" value={valueOf(params, "return_view")}/>}<input type="hidden" name="return_competence" value={returnCompetence}/>{valueOf(params, "income_order") && <input type="hidden" name="income_order" value={valueOf(params, "income_order")}/>} {valueOf(params, "expense_order") && <input type="hidden" name="expense_order" value={valueOf(params, "expense_order")}/>}<EntryFields workspace={workspace} entry={entry}/><div className="md:col-span-4"><SaveButton/></div></form></FormPanel>}</article>;
}

export function MovementsView({ workspace, page, filters, params, canEdit, canAdmin }: { workspace: FinanceWorkspace; page: FinancialEntryPage; filters: FinanceFilters; params: SearchParams; canEdit: boolean; canAdmin: boolean }) {
  const trail = valueOf(params, "trail");
  const keep = new URLSearchParams();
  for (const key of ["view", "competence", "account", "card", "category", "person", "property", "status", "type", "realization", "q"]) { const value = valueOf(params, key); if (value) keep.set(key, value); }
  const previous = previousCursorTrail(trail);
  const prevQuery = new URLSearchParams(keep); if (previous.cursor) prevQuery.set("cursor", previous.cursor); if (previous.trail) prevQuery.set("trail", previous.trail);
  const nextQuery = new URLSearchParams(keep); if (page.nextCursor) { nextQuery.set("cursor", page.nextCursor); nextQuery.set("trail", appendCursorTrail(trail, page.nextCursor)); }
  const people = workspace.people.map((person) => ({ id: person.id, label: `${person.first_name} ${person.last_name}` }));
  return <div className="space-y-5"><form className={`${panel} grid gap-3 sm:grid-cols-2 lg:grid-cols-6`}><input type="hidden" name="view" value="movements"/>
    <FieldLabel label="Buscar" help="Localiza lançamentos pelo texto da descrição."><input name="q" defaultValue={filters.query} placeholder="Buscar descrição" className={`block w-full ${field}`}/></FieldLabel>
    <FieldLabel label="Competência" help="Exibe somente os lançamentos do mês selecionado."><input name="competence" type="month" defaultValue={filters.competence?.slice(0, 7)} className={`block w-full ${field}`}/></FieldLabel>
    <FieldLabel label="Conta" help="Filtra os lançamentos vinculados à conta selecionada."><select name="account" defaultValue={filters.accountId} className={`block w-full ${field}`}><Options placeholder="Todas as contas" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select></FieldLabel>
    <FieldLabel label="Cartão" help="Filtra os lançamentos agrupados no cartão selecionado."><select name="card" defaultValue={filters.cardId} className={`block w-full ${field}`}><Options placeholder="Todos os cartões" rows={workspace.cards.map((item) => ({ id: item.id, label: item.name }))}/></select></FieldLabel>
    <FieldLabel label="Categoria" help="Filtra pela categoria principal ou pela classificação complementar do lançamento."><select name="category" defaultValue={filters.categoryId} className={`block w-full ${field}`}><Options placeholder="Todas as categorias" rows={workspace.categories.map((item) => ({ id: item.id, label: item.name }))}/></select></FieldLabel>
    <FieldLabel label="Status" help="Restringe a lista à etapa operacional selecionada, como planejado, pago ou vencido."><select name="status" defaultValue={filters.status} className={`block w-full ${field}`}><option value="">Todos os status</option><option value="planned">Planejado</option><option value="payable">A pagar</option><option value="receivable">A receber</option><option value="paid">Pago</option><option value="received">Recebido</option><option value="overdue">Vencido</option></select></FieldLabel>
    <FieldLabel label="Pessoa" help="Filtra pela pessoa responsável ou economicamente relacionada ao lançamento."><select name="person" defaultValue={filters.personId} className={`block w-full ${field}`}><Options placeholder="Todas as pessoas" rows={people}/></select></FieldLabel>
    <FieldLabel label="Imóvel" help="Exibe os lançamentos relacionados ao imóvel selecionado."><select name="property" defaultValue={filters.propertyId} className={`block w-full ${field}`}><Options placeholder="Todos os imóveis" rows={workspace.properties.map((item) => ({ id: item.id, label: item.title }))}/></select></FieldLabel>
    <FieldLabel label="Natureza" help="Separa receitas de despesas; em branco mantém ambas na consulta."><select name="type" defaultValue={filters.entryType} className={`block w-full ${field}`}><option value="">Receitas e despesas</option><option value="income">Receita</option><option value="expense">Despesa</option></select></FieldLabel>
    <FieldLabel label="Realização" help="Permite mostrar todos, somente valores previstos ou somente valores já realizados."><select name="realization" defaultValue={filters.realization} className={`block w-full ${field}`}><option value="">Previsto e realizado</option><option value="expected">Somente previsto</option><option value="actual">Somente realizado</option></select></FieldLabel>
    <div className="flex items-end"><button className={`${primary} w-full`}>Filtrar</button></div><div className="flex items-end"><Link href="/financas?view=movements" className="w-full rounded-xl border px-4 py-2.5 text-center text-sm">Limpar</Link></div></form>
    {canEdit && <div className="grid gap-5 lg:grid-cols-2">
      <FormPanel title="Novo lançamento"><DuplicateAmountForm action={createEntry} amountField="expected_amount" className="grid gap-3 md:grid-cols-2"><EntryFields workspace={workspace} defaultCompetence={filters.competence}/><div className="md:col-span-2"><SaveButton label="Criar lançamento"/></div></DuplicateAmountForm></FormPanel>
      <div className="space-y-5">
        <FormPanel title="Ajustar saldo de conta"><p className="mb-4 text-sm text-slate-600">Correção pontual e não recorrente. Altera o saldo da conta a partir da data informada, sem alterar receitas, despesas, resultado do mês ou projeção operacional.</p><form action={createBalanceAdjustment} className="grid gap-3 sm:grid-cols-2">
          <FieldLabel label="Conta" help="Conta cujo saldo real precisa ser corrigido."><select name="account_id" required className={`block w-full ${field}`}><Options placeholder="Selecione a conta" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select></FieldLabel>
          <FieldLabel label="Tipo de correção" help="Reduzir registra uma saída de ajuste; aumentar registra uma entrada de ajuste."><select name="adjustment_direction" required defaultValue="outflow" className={`block w-full ${field}`}><option value="outflow">Reduzir saldo</option><option value="inflow">Aumentar saldo</option></select></FieldLabel>
          <FieldLabel label="Valor" help="Diferença positiva entre o saldo calculado e o saldo real. Não informe sinal negativo."><input name="amount" required inputMode="decimal" className={`block w-full ${field}`}/></FieldLabel>
          <FieldLabel label="Competência" help="Mês em que a correção passa a compor o saldo."><input name="competence" required type="month" defaultValue={(filters.competence ?? currentCompetence()).slice(0, 7)} className={`block w-full ${field}`}/></FieldLabel>
          <FieldLabel label="Data efetiva" help="Data em que o saldo real foi conferido e corrigido."><input name="effective_date" required type="date" className={`block w-full ${field}`}/></FieldLabel>
          <FieldLabel label="Motivo" help="Descrição opcional para auditoria futura."><input name="description" placeholder="Ex.: conciliação bancária" className={`block w-full ${field}`}/></FieldLabel>
          <div className="sm:col-span-2"><SaveButton label="Aplicar ajuste"/></div>
        </form></FormPanel>
        <FormPanel title="Transferir entre contas"><p className="mb-4 text-sm text-slate-600">Move dinheiro entre contas sem alterar receitas, despesas ou o total consolidado.</p><form action={createTransfer} className="grid gap-3 sm:grid-cols-2"><FieldLabel label="Conta de origem" help="Conta que terá o saldo reduzido."><select name="from_account_id" required className={`block w-full ${field}`}><Options placeholder="Selecione a origem" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select></FieldLabel><FieldLabel label="Conta de destino" help="Conta que receberá o mesmo valor; a soma das contas não muda."><select name="to_account_id" required className={`block w-full ${field}`}><Options placeholder="Selecione o destino" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select></FieldLabel><FieldLabel label="Valor" help="Valor positivo transferido entre as duas contas."><input name="amount" required inputMode="decimal" className={`block w-full ${field}`}/></FieldLabel><FieldLabel label="Competência" help="Mês de referência da transferência."><input name="competence" required type="month" defaultValue={(filters.competence ?? currentCompetence()).slice(0, 7)} className={`block w-full ${field}`}/></FieldLabel><FieldLabel label="Data efetiva" help="Data em que a transferência aconteceu."><input name="effective_date" required type="date" className={`block w-full ${field}`}/></FieldLabel><FieldLabel label="Descrição" help="Identificação opcional para consulta futura."><input name="description" placeholder="Ex.: Bradesco para Cofre" className={`block w-full ${field}`}/></FieldLabel><div className="sm:col-span-2"><SaveButton label="Transferir"/></div></form></FormPanel>
      </div>
    </div>}
    <section className={panel}><div><h2 className="font-semibold">Movimentações</h2><p className="text-sm text-slate-500">Até 25 registros por página, sem repetição entre cursores.</p></div>{page.entries.length ? <div className="mt-4 space-y-3">{page.entries.map((entry) => <MovementCard key={entry.id} workspace={workspace} entry={entry} params={params} canEdit={canEdit} canAdmin={canAdmin}/>)}</div> : <Empty>Nenhum lançamento encontrado para os filtros.</Empty>}<nav aria-label="Paginação de movimentações" className="mt-5 flex items-center justify-between gap-3"><Link aria-disabled={!trail} href={trail ? `/financas?${prevQuery}` : "#"} className={`rounded-xl border px-4 py-2 text-sm font-semibold ${trail ? "text-slate-700" : "pointer-events-none text-slate-300"}`}>Anterior</Link><span className="text-xs text-slate-500">Cursor seguro</span><Link aria-disabled={!page.hasMore} href={page.hasMore ? `/financas?${nextQuery}` : "#"} className={`rounded-xl border px-4 py-2 text-sm font-semibold ${page.hasMore ? "text-slate-700" : "pointer-events-none text-slate-300"}`}>Próxima</Link></nav></section></div>;
}
