import Link from "next/link";
import { ConfirmSubmitButton } from "@/app/components/confirm-submit-button";
import { createEntry, createTransfer, markEntryPaid, undoEntryPayment, updateEntry } from "@/app/financas/actions";
import { appendCursorTrail, previousCursorTrail } from "@/lib/finance/pagination";
import { currentCompetence } from "@/lib/finance/services";
import type { FinanceFilters, FinancialEntryPage, FinancialEntryRow, FinanceWorkspace } from "@/lib/finance/types";
import { ArchiveForm, currency, danger, Empty, EntryFields, field, formatDate, FormPanel, Options, panel, primary, SaveButton } from "@/app/financas/views/shared";

type SearchParams = Record<string, string | string[] | undefined>;
function valueOf(params: SearchParams, key: string) { const value = params[key]; return Array.isArray(value) ? value[0] : value; }

function History({ workspace, entryId }: { workspace: FinanceWorkspace; entryId: string }) {
  const history = workspace.history.filter((item) => item.financial_entry_id === entryId);
  return <details className="mt-3 rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer text-xs font-semibold text-sky-700">Histórico somente leitura ({history.length})</summary>{history.length ? <ol className="mt-2 space-y-2">{history.map((item) => <li key={item.id} className="text-xs text-slate-600"><span className="font-medium">{item.change_type}</span> · {formatDate(item.changed_at)}</li>)}</ol> : <p className="mt-2 text-xs text-slate-500">Nenhuma alteração registrada.</p>}</details>;
}

function MovementCard({ workspace, entry, params, canEdit, canAdmin }: { workspace: FinanceWorkspace; entry: FinancialEntryRow; params: SearchParams; canEdit: boolean; canAdmin: boolean }) {
  const category = workspace.categories.find((item) => item.id === entry.category_id)?.name ?? "Sem categoria";
  const classification = workspace.categories.find((item) => item.id === entry.classification_category_id)?.name;
  const source = workspace.accounts.find((item) => item.id === entry.account_id)?.institution ?? workspace.cards.find((item) => item.id === entry.card_id)?.name ?? entry.origin;
  return <article className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{entry.description}</p><p className="text-xs text-slate-500">{formatDate(entry.expected_date ?? entry.due_date ?? entry.competence)} · {category}{classification ? ` · Tipo: ${classification}` : ""} · {source}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{entry.status}</span></div><dl className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-xs text-slate-500">Previsto</dt><dd>{currency.format(entry.expected_amount)}</dd></div><div><dt className="text-xs text-slate-500">Realizado</dt><dd>{entry.actual_amount === null ? "—" : currency.format(entry.actual_amount)}</dd></div><div><dt className="text-xs text-slate-500">Diferença</dt><dd>{entry.difference_amount === null ? "—" : currency.format(entry.difference_amount)}</dd></div></dl>{canEdit && <div className="mt-4 flex flex-wrap gap-2">{entry.actual_amount === null ? <form action={markEntryPaid} className="flex flex-wrap gap-2"><input type="hidden" name="id" value={entry.id}/><input name="actual_amount" defaultValue={entry.expected_amount} aria-label="Valor realizado" className={`${field} w-28`}/><input name="effective_date" type="date" required aria-label="Data efetiva" className={field}/><SaveButton label="Realizar"/></form> : <form action={undoEntryPayment}><input type="hidden" name="id" value={entry.id}/><ConfirmSubmitButton label="Desfazer pagamento" confirmMessage="Deseja desfazer o valor realizado deste lançamento?" className={danger}/></form>}{canAdmin && <ArchiveForm id={entry.id} entity="entry"/>}</div>}<History workspace={workspace} entryId={entry.id}/>{canEdit && <FormPanel title="Editar lançamento"><form action={updateEntry} className="grid gap-3 md:grid-cols-4"><input type="hidden" name="id" value={entry.id}/>{valueOf(params, "return_view") && <input type="hidden" name="return_view" value={valueOf(params, "return_view")}/>}<input type="hidden" name="return_competence" value={valueOf(params, "return_competence") ?? entry.competence.slice(0, 7)}/>{valueOf(params, "income_order") && <input type="hidden" name="income_order" value={valueOf(params, "income_order")}/>} {valueOf(params, "expense_order") && <input type="hidden" name="expense_order" value={valueOf(params, "expense_order")}/>}<EntryFields workspace={workspace} entry={entry}/><div className="md:col-span-4"><SaveButton/></div></form></FormPanel>}</article>;
}

export function MovementsView({ workspace, page, filters, params, canEdit, canAdmin }: { workspace: FinanceWorkspace; page: FinancialEntryPage; filters: FinanceFilters; params: SearchParams; canEdit: boolean; canAdmin: boolean }) {
  const trail = valueOf(params, "trail");
  const keep = new URLSearchParams();
  for (const key of ["view", "competence", "account", "card", "category", "person", "property", "status", "type", "realization", "q"]) { const value = valueOf(params, key); if (value) keep.set(key, value); }
  const previous = previousCursorTrail(trail);
  const prevQuery = new URLSearchParams(keep); if (previous.cursor) prevQuery.set("cursor", previous.cursor); if (previous.trail) prevQuery.set("trail", previous.trail);
  const nextQuery = new URLSearchParams(keep); if (page.nextCursor) { nextQuery.set("cursor", page.nextCursor); nextQuery.set("trail", appendCursorTrail(trail, page.nextCursor)); }
  const people = workspace.people.map((person) => ({ id: person.id, label: `${person.first_name} ${person.last_name}` }));
  return <div className="space-y-5"><form className={`${panel} grid gap-3 sm:grid-cols-2 lg:grid-cols-6`}><input type="hidden" name="view" value="movements"/><input name="q" defaultValue={filters.query} placeholder="Buscar descrição" className={field}/><input name="competence" type="month" defaultValue={filters.competence?.slice(0, 7)} className={field}/><select name="account" defaultValue={filters.accountId} className={field}><Options placeholder="Todas as contas" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select><select name="card" defaultValue={filters.cardId} className={field}><Options placeholder="Todos os cartões" rows={workspace.cards.map((item) => ({ id: item.id, label: item.name }))}/></select><select name="category" defaultValue={filters.categoryId} className={field}><Options placeholder="Todas as categorias" rows={workspace.categories.map((item) => ({ id: item.id, label: item.name }))}/></select><select name="status" defaultValue={filters.status} className={field}><option value="">Todos os status</option><option value="planned">Planejado</option><option value="payable">A pagar</option><option value="receivable">A receber</option><option value="paid">Pago</option><option value="received">Recebido</option><option value="overdue">Vencido</option></select><select name="person" defaultValue={filters.personId} className={field}><Options placeholder="Todas as pessoas" rows={people}/></select><select name="property" defaultValue={filters.propertyId} className={field}><Options placeholder="Todos os imóveis" rows={workspace.properties.map((item) => ({ id: item.id, label: item.title }))}/></select><select name="type" defaultValue={filters.entryType} className={field}><option value="">Receitas e despesas</option><option value="income">Receita</option><option value="expense">Despesa</option></select><select name="realization" defaultValue={filters.realization} className={field}><option value="">Previsto e realizado</option><option value="expected">Somente previsto</option><option value="actual">Somente realizado</option></select><button className={primary}>Filtrar</button><Link href="/financas?view=movements" className="rounded-xl border px-4 py-2.5 text-center text-sm">Limpar</Link></form>
    {canEdit && <div className="grid gap-5 lg:grid-cols-2"><FormPanel title="Novo lançamento"><form action={createEntry} className="grid gap-3 md:grid-cols-2"><EntryFields workspace={workspace}/><div className="md:col-span-2"><SaveButton label="Criar lançamento"/></div></form></FormPanel><FormPanel title="Transferir entre contas"><form action={createTransfer} className="grid gap-3 sm:grid-cols-2"><select name="from_account_id" required className={field}><Options placeholder="Conta de origem" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select><select name="to_account_id" required className={field}><Options placeholder="Conta de destino" rows={workspace.accounts.map((item) => ({ id: item.id, label: item.institution }))}/></select><input name="amount" required inputMode="decimal" placeholder="Valor" className={field}/><input name="competence" required type="month" defaultValue={currentCompetence().slice(0, 7)} className={field}/><input name="effective_date" required type="date" className={field}/><input name="description" placeholder="Descrição" className={field}/><div className="sm:col-span-2"><SaveButton label="Transferir"/></div></form></FormPanel></div>}
    <section className={panel}><div><h2 className="font-semibold">Movimentações</h2><p className="text-sm text-slate-500">Até 25 registros por página, sem repetição entre cursores.</p></div>{page.entries.length ? <div className="mt-4 space-y-3">{page.entries.map((entry) => <MovementCard key={entry.id} workspace={workspace} entry={entry} params={params} canEdit={canEdit} canAdmin={canAdmin}/>)}</div> : <Empty>Nenhum lançamento encontrado para os filtros.</Empty>}<nav aria-label="Paginação de movimentações" className="mt-5 flex items-center justify-between gap-3"><Link aria-disabled={!trail} href={trail ? `/financas?${prevQuery}` : "#"} className={`rounded-xl border px-4 py-2 text-sm font-semibold ${trail ? "text-slate-700" : "pointer-events-none text-slate-300"}`}>Anterior</Link><span className="text-xs text-slate-500">Cursor seguro</span><Link aria-disabled={!page.hasMore} href={page.hasMore ? `/financas?${nextQuery}` : "#"} className={`rounded-xl border px-4 py-2 text-sm font-semibold ${page.hasMore ? "text-slate-700" : "pointer-events-none text-slate-300"}`}>Próxima</Link></nav></section></div>;
}
